os:
  - osx
  - linux
language: cpp
compiler:
  - clang
addons:
  homebrew:
    packages:
      - cmake
      - qt
      - ninja
  apt:
    packages:
      - cmake
      - qt5-default
      - ninja-build
matrix:
  include:
    - os: osx
      env: QT_PREFIX=$(brew --prefix qt)
    - os: linux
      env: QT_PREFIX=""
before_script:
  - mkdir "build/"
  - cd "build/"
  - cmake "-DCMAKE_PREFIX_PATH=$QT_PREFIX" -GNinja ../src
script:
  - ninja
after_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $QT_PREFIX/bin/macdeployqt Cygnus.app -dmg; fi
