language: cpp
addons:
  homebrew:
    packages:
      - cmake
      - qt
      - ninja
  apt:
    packages:
      - cmake
      - qt5-default
      - ninja-build
      - libstdc++6
matrix:
  include:
    - name: "OSX Release (Clang)"
      os: osx
      env: QT_PREFIX=$(brew --prefix qt)
      compiler: clang
    - name: "OSX Release (GCC)"
      os: osx
      env: QT_PREFIX=$(brew --prefix qt)
      compiler: gcc
    - name: "Linux Release (Clang)"
      os: linux
      env: QT_PREFIX=""
      compiler: clang
    - name: "Linux Release (GCC)"
      os: linux
      env: QT_PREFIX=""
      compiler: gcc
before_script:
  - mkdir "build/"
  - cd "build/"
  - cmake "-DCMAKE_PREFIX_PATH=$QT_PREFIX" -GNinja ../src
script:
  - ninja
after_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $QT_PREFIX/bin/macdeployqt Cygnus.app -dmg; fi
