name: Create Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Configure CMake
      run: |
        mkdir -p ${{ runner.workspace }}\build
        cd ${{ runner.workspace }}\build
        cmake.exe -DCMAKE_BUILD_TYPE=Release ${{ github.workspace }}\src
    - name: Build
      run: |
        cd ${{ runner.workspace }}\build
        cmake.exe --build .
    - name: QT Deploy
      run: Move-Item ${{ runner.workspace }}\build\cygnus.exe ${{ runner.workspace }}\deploy
    - name: makensis
      uses: joncloud/makensis-action@v1
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: CygnusCrosswordsSetup.exe
        path: ${{ runner.workspace }}\CygnusCrosswordsSetup.exe
